// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple/simple.proto

package simple

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type OrderMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                uint64   `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMessage) Reset()         { *m = OrderMessage{} }
func (m *OrderMessage) String() string { return proto.CompactTextString(m) }
func (*OrderMessage) ProtoMessage()    {}
func (*OrderMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{1}
}

func (m *OrderMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMessage.Unmarshal(m, b)
}
func (m *OrderMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMessage.Marshal(b, m, deterministic)
}
func (m *OrderMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMessage.Merge(m, src)
}
func (m *OrderMessage) XXX_Size() int {
	return xxx_messageInfo_OrderMessage.Size(m)
}
func (m *OrderMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMessage proto.InternalMessageInfo

func (m *OrderMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderMessage) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderMessage) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type TradeMessage struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int32                `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int32                `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TradeMessage) Reset()         { *m = TradeMessage{} }
func (m *TradeMessage) String() string { return proto.CompactTextString(m) }
func (*TradeMessage) ProtoMessage()    {}
func (*TradeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{2}
}

func (m *TradeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeMessage.Unmarshal(m, b)
}
func (m *TradeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeMessage.Marshal(b, m, deterministic)
}
func (m *TradeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeMessage.Merge(m, src)
}
func (m *TradeMessage) XXX_Size() int {
	return xxx_messageInfo_TradeMessage.Size(m)
}
func (m *TradeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TradeMessage proto.InternalMessageInfo

func (m *TradeMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TradeMessage) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeMessage) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *TradeMessage) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "simple.Empty")
	proto.RegisterType((*OrderMessage)(nil), "simple.OrderMessage")
	proto.RegisterType((*TradeMessage)(nil), "simple.TradeMessage")
}

func init() { proto.RegisterFile("simple/simple.proto", fileDescriptor_9b3c868e94d57426) }

var fileDescriptor_9b3c868e94d57426 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0xeb, 0xbe, 0x4d, 0xdf, 0xf6, 0xfa, 0x67, 0x30, 0x1d, 0xa2, 0x2c, 0x44, 0x99, 0x32,
	0x25, 0x28, 0xb0, 0x20, 0x31, 0x21, 0x55, 0x4c, 0x08, 0x29, 0xcd, 0xc4, 0xe6, 0xd6, 0x47, 0x64,
	0xa9, 0x4e, 0x8c, 0xe3, 0x0e, 0xf9, 0x12, 0x7c, 0x53, 0xbe, 0x03, 0x92, 0x9d, 0xa0, 0x20, 0x8a,
	0x60, 0xb2, 0xef, 0xf4, 0x9c, 0x9f, 0x7b, 0x7e, 0x32, 0x5c, 0x34, 0x42, 0xaa, 0x23, 0xa6, 0xee,
	0x48, 0x94, 0xae, 0x4d, 0x4d, 0xa7, 0xae, 0x0a, 0x2e, 0xcb, 0xba, 0x2e, 0x8f, 0x98, 0xda, 0xee,
	0xfe, 0xf4, 0x92, 0x1a, 0x21, 0xb1, 0x31, 0x4c, 0x2a, 0x27, 0x8c, 0xfe, 0x83, 0xb7, 0x95, 0xca,
	0xb4, 0x11, 0x87, 0xe5, 0x93, 0xe6, 0xa8, 0x1f, 0xb1, 0x69, 0x58, 0x89, 0x74, 0x0d, 0x63, 0xc1,
	0x7d, 0x12, 0x92, 0xd8, 0xcb, 0xc7, 0x82, 0xd3, 0x0d, 0x78, 0x4a, 0x8b, 0x03, 0xfa, 0xe3, 0x90,
	0xc4, 0x93, 0xdc, 0x15, 0x34, 0x80, 0xd9, 0xeb, 0x89, 0x55, 0x46, 0x98, 0xd6, 0xff, 0x17, 0x92,
	0x78, 0x95, 0x7f, 0xd6, 0x94, 0xc2, 0xc4, 0xb4, 0x0a, 0xfd, 0x49, 0x48, 0xe2, 0x79, 0x6e, 0xef,
	0xd1, 0x1b, 0x81, 0x65, 0xa1, 0x19, 0xc7, 0x3f, 0xd9, 0x78, 0x3f, 0xd9, 0x78, 0x03, 0x9b, 0x3b,
	0x58, 0x1c, 0x34, 0x32, 0x83, 0xbc, 0x10, 0xd2, 0xb9, 0x2d, 0xb2, 0x20, 0x71, 0xc1, 0x93, 0x3e,
	0x78, 0x52, 0xf4, 0xc1, 0xf3, 0xa1, 0x3c, 0x7b, 0x27, 0xb0, 0xb0, 0x0b, 0x6d, 0xab, 0x52, 0x54,
	0x48, 0x33, 0x98, 0x37, 0x58, 0x71, 0x8b, 0x82, 0x6e, 0x92, 0x0e, 0xea, 0x90, 0x4c, 0xb0, 0xea,
	0xbb, 0x0e, 0xdc, 0x88, 0xde, 0xc2, 0xfa, 0x01, 0x8d, 0xd5, 0xec, 0x8c, 0x46, 0x26, 0xe9, 0x57,
	0x49, 0x70, 0xf6, 0x9d, 0x68, 0x74, 0x45, 0xba, 0x51, 0xbb, 0xc0, 0x2f, 0xa3, 0x43, 0x6a, 0x76,
	0xf4, 0x06, 0xe6, 0x3b, 0xac, 0xb8, 0xed, 0xd3, 0xb3, 0xb2, 0x6f, 0x9b, 0xc6, 0xe4, 0x7e, 0xf6,
	0xdc, 0x7d, 0x8d, 0xfd, 0xd4, 0xa2, 0xb9, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xfd, 0xcb,
	0x66, 0x40, 0x02, 0x00, 0x00,
}
