// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple/simple.proto

package simple

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Order struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                uint64   `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Trade struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int32                `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int32                `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{2}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Trade) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Trade) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

type OrderBook struct {
	BuyOrder             *Order   `protobuf:"bytes,1,opt,name=buyOrder,proto3" json:"buyOrder,omitempty"`
	SellOrder            *Order   `protobuf:"bytes,2,opt,name=sellOrder,proto3" json:"sellOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBook) Reset()         { *m = OrderBook{} }
func (m *OrderBook) String() string { return proto.CompactTextString(m) }
func (*OrderBook) ProtoMessage()    {}
func (*OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b3c868e94d57426, []int{3}
}

func (m *OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBook.Unmarshal(m, b)
}
func (m *OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBook.Marshal(b, m, deterministic)
}
func (m *OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBook.Merge(m, src)
}
func (m *OrderBook) XXX_Size() int {
	return xxx_messageInfo_OrderBook.Size(m)
}
func (m *OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBook proto.InternalMessageInfo

func (m *OrderBook) GetBuyOrder() *Order {
	if m != nil {
		return m.BuyOrder
	}
	return nil
}

func (m *OrderBook) GetSellOrder() *Order {
	if m != nil {
		return m.SellOrder
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "simple.Empty")
	proto.RegisterType((*Order)(nil), "simple.Order")
	proto.RegisterType((*Trade)(nil), "simple.Trade")
	proto.RegisterType((*OrderBook)(nil), "simple.OrderBook")
}

func init() { proto.RegisterFile("simple/simple.proto", fileDescriptor_9b3c868e94d57426) }

var fileDescriptor_9b3c868e94d57426 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xbb, 0x4e, 0xf3, 0x30,
	0x14, 0xae, 0xf3, 0xd7, 0xfd, 0x9b, 0x13, 0xb5, 0x83, 0x61, 0x88, 0xb2, 0x10, 0x65, 0x0a, 0x42,
	0xa4, 0x28, 0xac, 0x4c, 0x95, 0x2a, 0x46, 0xa4, 0xb4, 0x13, 0x12, 0x43, 0x5a, 0x1f, 0x2a, 0x8b,
	0xdc, 0x70, 0xdd, 0x21, 0x4f, 0xc0, 0xf3, 0xf1, 0x46, 0x48, 0xc7, 0x6d, 0x68, 0xc4, 0x6d, 0x4a,
	0x3e, 0x7f, 0x17, 0xfb, 0xf3, 0x31, 0x9c, 0xed, 0x54, 0xd9, 0x14, 0x38, 0xb3, 0x9f, 0xa4, 0xd1,
	0xb5, 0xa9, 0xc5, 0xc8, 0xa2, 0xe0, 0x62, 0x5b, 0xd7, 0xdb, 0x02, 0x67, 0xb4, 0xba, 0xde, 0x3f,
	0xcf, 0x8c, 0x2a, 0x71, 0x67, 0xf2, 0xb2, 0xb1, 0xc2, 0xe8, 0x3f, 0xf0, 0x45, 0xd9, 0x98, 0x36,
	0x7a, 0x02, 0xfe, 0xa0, 0x25, 0x6a, 0x31, 0x05, 0x47, 0x49, 0x9f, 0x85, 0x2c, 0xe6, 0x99, 0xa3,
	0xa4, 0x38, 0x07, 0xde, 0x68, 0xb5, 0x41, 0xdf, 0x09, 0x59, 0x3c, 0xcc, 0x2c, 0x10, 0x01, 0x8c,
	0x5f, 0xf7, 0x79, 0x65, 0x94, 0x69, 0xfd, 0x7f, 0x21, 0x8b, 0x27, 0x59, 0x87, 0x85, 0x80, 0xa1,
	0x69, 0x1b, 0xf4, 0x87, 0x21, 0x8b, 0xdd, 0x8c, 0xfe, 0xa3, 0x37, 0x06, 0x7c, 0xa5, 0x73, 0x89,
	0xbf, 0xe7, 0xf3, 0x9f, 0xf2, 0xf9, 0x49, 0xfe, 0x1d, 0x78, 0x1b, 0x8d, 0xb9, 0x41, 0xb9, 0x52,
	0xa5, 0xdd, 0xc6, 0x4b, 0x83, 0xc4, 0x56, 0x4d, 0x8e, 0x55, 0x93, 0xd5, 0xb1, 0x6a, 0x76, 0x2a,
	0x8f, 0x36, 0xe0, 0x52, 0xd1, 0x79, 0x5d, 0xbf, 0x88, 0x4b, 0x18, 0xaf, 0xf7, 0x2d, 0x61, 0x3a,
	0x92, 0x97, 0x4e, 0x92, 0xc3, 0x45, 0xd2, 0x62, 0xd6, 0xd1, 0xe2, 0x0a, 0xdc, 0x1d, 0x16, 0x85,
	0xd5, 0x3a, 0xdf, 0x69, 0x3f, 0xf9, 0xf4, 0x9d, 0x81, 0x47, 0x75, 0x17, 0xd5, 0x56, 0x55, 0x68,
	0xcd, 0x95, 0xb4, 0x49, 0x7d, 0x5b, 0xd0, 0x41, 0x3b, 0x88, 0x81, 0x48, 0x61, 0x7a, 0x8f, 0x86,
	0xc8, 0xa5, 0xd1, 0x98, 0x97, 0xa2, 0x2f, 0x09, 0xfa, 0x01, 0xd1, 0xe0, 0x86, 0x1d, 0x3c, 0xb4,
	0xe5, 0x1f, 0x1e, 0xd2, 0x90, 0xe7, 0x1a, 0xdc, 0x25, 0x56, 0xd2, 0x8e, 0xa5, 0xcf, 0x7f, 0x39,
	0x54, 0xcc, 0xe6, 0xe3, 0xc7, 0xc3, 0xab, 0x5a, 0x8f, 0xe8, 0x8e, 0x6f, 0x3f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x63, 0x45, 0x58, 0x9f, 0x7b, 0x02, 0x00, 0x00,
}
